all: ha hb hc hd ia ib ic id

ha:
	-gcc -o heapsort heapsort.c
hb:
	-gcc -o heapsortForking heapsortForking.c -pthread
hc:
	-gcc -o heapsortOpenMp heapsortOpenMp.c
hd:
	-gcc -o heapsortPthread heapsortPthread.c -pthread

ia:
	-gcc -o insertionSort insertionSort.c
ib:
	-gcc -o insertionSortForking insertionForking.c
ic:
	-gcc -o insertionSortOpenMp insertionSortOpenMp.c
id:
	-gcc -o insertionSortPthread insertionSortPthread.c

