all: problem1 problem2 problem3 problem4 problem5

problem1:
	-gcc -o problem1 problem1.c -fopenmp -lm
problem2:
	-gcc -o problem2 problem2.c -pthread -lm
problem3:
	-gcc -o problem3 problem3.c -lrt -lm
problem4:
	-gcc -o problem4 problem4.c -lrt -pthread -lm
problem5:
	-gcc -o problem5 problem5.c -lrt -lm -pthread
